#!/bin/bash

# The following symbols (past the first five) are taken from the public headers.
# A list of the latter should be available Makefile.sources/LIBDRM_LIMA_H_FILES

FUNCS=$(nm -D --format=bsd --defined-only ${1-.libs/libdrm_lima.so} | awk '{print $3}'| while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
__bss_start
_edata
_end
_fini
_init
lima_device_create
lima_device_delete
lima_device_query_info
EOF
done)

test ! -n "$FUNCS" || echo $FUNCS
test ! -n "$FUNCS"
